# Generated by Django 4.2.1 on 2023-06-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MOBILE', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varient_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to='product_images/')),
                ('image1', models.ImageField(null=True, upload_to='product_images/')),
                ('image2', models.ImageField(null=True, upload_to='product_images/')),
                ('product_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MOBILE.product')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MOBILE.varient'),
        ),
        migrations.AddField(
            model_name='order',
            name='varient_Key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MOBILE.varient'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wish_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MOBILE.varient'),
        ),
    ]
