# Generated by Django 4.2.1 on 2023-06-25 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MOBILE', '0005_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='copuon_category',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='category',
            name='catewise_dicount_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_dis_amount',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_minmun_amount',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('w_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MOBILE.uuser')),
            ],
        ),
    ]
