# Generated by Django 4.2.1 on 2023-06-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MOBILE', '0006_remove_coupon_active_remove_coupon_copuon_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient',
            name='catogery_offer_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='varient',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Couponapplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.CharField(max_length=50)),
                ('c_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MOBILE.uuser')),
            ],
        ),
    ]
