# Generated by Django 4.2.1 on 2023-06-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOBILE', '0007_varient_catogery_offer_price_alter_varient_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponapplied',
            name='c_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
